### PR TITLE
Iamngoni-covid-19-tracker-getcurrentdate

### PR DESCRIPTION
**Pull request by iamNGVJ**

### CODE REVIEW

**Comment by alistairholmes** [comment]
Hi please share screenshot of the app so that I can see the changes.

**Comment by iamNGVJ** [comment]
file:///home/iamngoni/Pictures/Screenshot%20from%202020-04-01%2000-19-27.png
This first one has - the date (actual date)
                            - added right padding to the self check container (i feel it looks better this way)
file:///home/iamngoni/Pictures/Screenshot%20from%202020-04-01%2000-19-55.png
The second one just shows a minor change to the progress bar i.e. increased length (according to screen width). Also a minor change from I Agree, Proceed to I Agree

**Comment by alistairholmes** [comment]
Sorry images are not showing.

**Comment by iamNGVJ** [comment]
Screenshot from 2020-04-01 00-19-55

**Comment by iamNGVJ** [comment]
Screenshot from 2020-04-01 00-19-27

**Pull request merged**
